kind: Namespace
apiVersion: v1
metadata:
  name: zalenium
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: zalenium
  name: zalenium
  namespace: zalenium
spec:
  ports:
  - name: zalenium
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: zalenium
    role: grid
  type: NodePort
